[2023-06-06T00:55:57.049+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.is_1_api_available scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T00:55:57.063+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.is_1_api_available scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T00:55:57.064+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:55:57.064+0000] {taskinstance.py:1363} INFO - Starting attempt 8 of 11
[2023-06-06T00:55:57.064+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:55:57.084+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): group_users.is_1_api_available> on 2023-06-05 00:00:00+00:00
[2023-06-06T00:55:57.095+0000] {standard_task_runner.py:55} INFO - Started process 16262 to run task
[2023-06-06T00:55:57.099+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_weather_people_postgres', 'group_users.is_1_api_available', 'scheduled__2023-06-05T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/process_weather_people_postgres/process_weather_people_postgres.py', '--cfg-path', '/tmp/tmphg5tigtk']
[2023-06-06T00:55:57.101+0000] {standard_task_runner.py:83} INFO - Job 210: Subtask group_users.is_1_api_available
[2023-06-06T00:55:57.174+0000] {task_command.py:376} INFO - Running <TaskInstance: process_weather_people_postgres.group_users.is_1_api_available scheduled__2023-06-05T00:00:00+00:00 [running]> on host 1160da0dacdb
[2023-06-06T00:55:57.253+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=data_eng
AIRFLOW_CTX_DAG_ID=process_weather_people_postgres
AIRFLOW_CTX_TASK_ID=group_users.is_1_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-05T00:00:00+00:00
[2023-06-06T00:55:57.255+0000] {http.py:120} INFO - Poking: api/
[2023-06-06T00:55:57.268+0000] {base.py:71} INFO - Using connection ID 'random_people_api' for task execution.
[2023-06-06T00:55:57.270+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2023-06-06T00:55:57.710+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-06-06T00:55:57.721+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=process_weather_people_postgres, task_id=group_users.is_1_api_available, execution_date=20230605T000000, start_date=20230606T005557, end_date=20230606T005557
[2023-06-06T00:55:57.752+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-06-06T00:55:57.791+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
