[2023-06-06T00:24:47.169+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-06T00:24:47.181+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-06T00:24:47.181+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:24:47.181+0000] {taskinstance.py:1363} INFO - Starting attempt 7 of 10
[2023-06-06T00:24:47.181+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:24:47.196+0000] {taskinstance.py:1383} INFO - Executing <Task(ClimateNotificationSlackOperator): group_users.slack_notification_1> on 2023-06-04 00:00:00+00:00
[2023-06-06T00:24:47.205+0000] {standard_task_runner.py:55} INFO - Started process 14633 to run task
[2023-06-06T00:24:47.208+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_weather_people_postgres', 'group_users.slack_notification_1', 'scheduled__2023-06-04T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/process_weather_people_postgres/process_weather_people_postgres.py', '--cfg-path', '/tmp/tmpe9pucaj0']
[2023-06-06T00:24:47.209+0000] {standard_task_runner.py:83} INFO - Job 155: Subtask group_users.slack_notification_1
[2023-06-06T00:24:47.270+0000] {task_command.py:376} INFO - Running <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [running]> on host 1160da0dacdb
[2023-06-06T00:24:47.349+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=data_eng
AIRFLOW_CTX_DAG_ID=process_weather_people_postgres
AIRFLOW_CTX_TASK_ID=group_users.slack_notification_1
AIRFLOW_CTX_EXECUTION_DATE=2023-06-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-04T00:00:00+00:00
[2023-06-06T00:24:47.364+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-06-06T00:24:47.385+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/others/operators/climate_temperature_slack.py", line 58, in execute
    cursor.execute(self.sql)
psycopg2.errors.UndefinedColumn: column "id" does not exist
LINE 1:  SELECT id, city, lat, lon FROM bronze.user 
                ^

[2023-06-06T00:24:47.395+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=process_weather_people_postgres, task_id=group_users.slack_notification_1, execution_date=20230604T000000, start_date=20230606T002447, end_date=20230606T002447
[2023-06-06T00:24:47.407+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 155 for task group_users.slack_notification_1 (column "id" does not exist
LINE 1:  SELECT id, city, lat, lon FROM bronze.user 
                ^
; 14633)
[2023-06-06T00:24:47.420+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-06T00:24:47.447+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
